const char *
strTokenKind(enum TokenKind kind) {
    switch (kind) {
        case HALT:
            return "HALT";
        case LOAD:
            return "LOAD";
        case ADD:
            return "ADD";
        case MUL:
            return "MUL";
        case SUB:
            return "SUB";
        case DIV:
            return "DIV";
        case DOT_ALIGN:
            return "DOT_ALIGN";
        case DOT_BSS:
            return "DOT_BSS";
        case DOT_BYTE:
            return "DOT_BYTE";
        case DOT_DATA:
            return "DOT_DATA";
        case DOT_EQU:
            return "DOT_EQU";
        case DOT_GLOBAL:
            return "DOT_GLOBAL";
        case DOT_GLOBL:
            return "DOT_GLOBL";
        case DOT_LONG:
            return "DOT_LONG";
        case DOT_QUAD:
            return "DOT_QUAD";
        case DOT_STRING:
            return "DOT_STRING";
        case DOT_SPACE:
            return "DOT_SPACE";
        case DOT_TEXT:
            return "DOT_TEXT";
        case DOT_WORD:
            return "DOT_WORD";
        case EOI:
            return "EOI";
        case EMPTY_LABEL:
            return "EMPTY_LABEL";
        case UNKNOWN_TOKEN:
            return "UNKNOWN_TOKEN";
        case DECIMAL_LITERAL:
            return "DECIMAL_LITERAL";
        case OCTAL_LITERAL:
            return "OCTAL_LITERAL";
        case HEXADECIMAL_LITERAL:
            return "HEXADECIMAL_LITERAL";
        case CHARACTER_LITERAL:
            return "CHARACTER_LITERAL";
        case STRING_LITERAL:
            return "STRING_LITERAL";
        case IDENT:
            return "IDENT";
        case EOL:
            return "EOL";
        case PLUS:
            return "PLUS";
        case MINUS:
            return "MINUS";
        case ASTERISK:
            return "ASTERISK";
        case SLASH:
            return "SLASH";
        case PERCENT:
            return "PERCENT";
        case LATTENZAUN:
            return "LATTENZAUN";
        case KLAMMERAFFE:
            return "KLAMMERAFFE";
        case COLON:
            return "COLON";
        case COMMA:
            return "COMMA";
        case DOLLAR:
            return "DOLLAR";
        case LPAREN:
            return "LPAREN";
        case LPAREN_MEM:
            return "LPAREN_MEM";
        case RPAREN:
            return "RPAREN";
        case LBRACKET:
            return "LBRACKET";
        case RBRACKET:
            return "RBRACKET";
        case LBRACE:
            return "LBRACE";
        case RBRACE:
            return "RBRACE";
        case W0:
            return "W0";
        case W1:
            return "W1";
        case W2:
            return "W2";
        case W3:
            return "W3";
        case NUM_TOKENKIND: /* cause internal error */;
            ;
    }
    fprintf(stderr, "in 'valTokenKind': internal error\n");
    exit(1);
}
